name: 'Submodule Sync'

on:
  workflow_dispatch:

jobs:
  sync:
    name: 'Submodule Sync'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Commit update
      run: |
        git config --global user.name "David Ducos"
        git config --global user.email "david.ducos@gmail.com"
        git remote set-url origin https://x-access-token:${{ secrets.DAVIDDUCOS_TOKEN }}@github.com/mydumper/mydumper.git
        curl "https://github.com/mydumper/mydumper_repo/info/refs?service=git-upload-pack" --output ../latest_commit
        git update-index --cacheinfo 160000,$(head -2 ../latest_commit | tail -1 | cut -b9-48),repo
        git commit -am "Auto updated submodule references" && git push
